// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package user;

public final class ZCoin {
  private ZCoin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:user.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 user_id = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional int32 user_id = 1;</code>
     */
    int getUserId();

    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int64 mobile = 3;</code>
     */
    boolean hasMobile();
    /**
     * <code>optional int64 mobile = 3;</code>
     */
    long getMobile();

    /**
     * <code>optional string human_id = 4;</code>
     */
    boolean hasHumanId();
    /**
     * <code>optional string human_id = 4;</code>
     */
    java.lang.String getHumanId();
    /**
     * <code>optional string human_id = 4;</code>
     */
    com.google.protobuf.ByteString
        getHumanIdBytes();

    /**
     * <code>optional string password = 5;</code>
     */
    boolean hasPassword();
    /**
     * <code>optional string password = 5;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>optional string password = 5;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>optional double rc_amount = 6;</code>
     */
    boolean hasRcAmount();
    /**
     * <code>optional double rc_amount = 6;</code>
     */
    double getRcAmount();

    /**
     * <code>optional string role = 7 [default = "user"];</code>
     */
    boolean hasRole();
    /**
     * <code>optional string role = 7 [default = "user"];</code>
     */
    java.lang.String getRole();
    /**
     * <code>optional string role = 7 [default = "user"];</code>
     */
    com.google.protobuf.ByteString
        getRoleBytes();

    /**
     * <code>optional bool approved = 8 [default = false];</code>
     */
    boolean hasApproved();
    /**
     * <code>optional bool approved = 8 [default = false];</code>
     */
    boolean getApproved();

    /**
     * <code>optional string mail = 9;</code>
     */
    boolean hasMail();
    /**
     * <code>optional string mail = 9;</code>
     */
    java.lang.String getMail();
    /**
     * <code>optional string mail = 9;</code>
     */
    com.google.protobuf.ByteString
        getMailBytes();
  }
  /**
   * Protobuf type {@code user.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:user.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      userId_ = 0;
      name_ = "";
      mobile_ = 0L;
      humanId_ = "";
      password_ = "";
      rcAmount_ = 0D;
      role_ = "user";
      approved_ = false;
      mail_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              mobile_ = input.readInt64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              humanId_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              password_ = bs;
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              rcAmount_ = input.readDouble();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              role_ = bs;
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              approved_ = input.readBool();
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              mail_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return user.ZCoin.internal_static_user_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return user.ZCoin.internal_static_user_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              user.ZCoin.User.class, user.ZCoin.User.Builder.class);
    }

    private int bitField0_;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>optional int32 user_id = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 user_id = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOBILE_FIELD_NUMBER = 3;
    private long mobile_;
    /**
     * <code>optional int64 mobile = 3;</code>
     */
    public boolean hasMobile() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 mobile = 3;</code>
     */
    public long getMobile() {
      return mobile_;
    }

    public static final int HUMAN_ID_FIELD_NUMBER = 4;
    private volatile java.lang.Object humanId_;
    /**
     * <code>optional string human_id = 4;</code>
     */
    public boolean hasHumanId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string human_id = 4;</code>
     */
    public java.lang.String getHumanId() {
      java.lang.Object ref = humanId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          humanId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string human_id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getHumanIdBytes() {
      java.lang.Object ref = humanId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        humanId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 5;
    private volatile java.lang.Object password_;
    /**
     * <code>optional string password = 5;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string password = 5;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string password = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RC_AMOUNT_FIELD_NUMBER = 6;
    private double rcAmount_;
    /**
     * <code>optional double rc_amount = 6;</code>
     */
    public boolean hasRcAmount() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional double rc_amount = 6;</code>
     */
    public double getRcAmount() {
      return rcAmount_;
    }

    public static final int ROLE_FIELD_NUMBER = 7;
    private volatile java.lang.Object role_;
    /**
     * <code>optional string role = 7 [default = "user"];</code>
     */
    public boolean hasRole() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string role = 7 [default = "user"];</code>
     */
    public java.lang.String getRole() {
      java.lang.Object ref = role_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          role_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string role = 7 [default = "user"];</code>
     */
    public com.google.protobuf.ByteString
        getRoleBytes() {
      java.lang.Object ref = role_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        role_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPROVED_FIELD_NUMBER = 8;
    private boolean approved_;
    /**
     * <code>optional bool approved = 8 [default = false];</code>
     */
    public boolean hasApproved() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional bool approved = 8 [default = false];</code>
     */
    public boolean getApproved() {
      return approved_;
    }

    public static final int MAIL_FIELD_NUMBER = 9;
    private volatile java.lang.Object mail_;
    /**
     * <code>optional string mail = 9;</code>
     */
    public boolean hasMail() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string mail = 9;</code>
     */
    public java.lang.String getMail() {
      java.lang.Object ref = mail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mail_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string mail = 9;</code>
     */
    public com.google.protobuf.ByteString
        getMailBytes() {
      java.lang.Object ref = mail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, mobile_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, humanId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, password_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, rcAmount_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, role_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBool(8, approved_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, mail_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, mobile_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, humanId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, password_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, rcAmount_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, role_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, approved_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, mail_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof user.ZCoin.User)) {
        return super.equals(obj);
      }
      user.ZCoin.User other = (user.ZCoin.User) obj;

      boolean result = true;
      result = result && (hasUserId() == other.hasUserId());
      if (hasUserId()) {
        result = result && (getUserId()
            == other.getUserId());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasMobile() == other.hasMobile());
      if (hasMobile()) {
        result = result && (getMobile()
            == other.getMobile());
      }
      result = result && (hasHumanId() == other.hasHumanId());
      if (hasHumanId()) {
        result = result && getHumanId()
            .equals(other.getHumanId());
      }
      result = result && (hasPassword() == other.hasPassword());
      if (hasPassword()) {
        result = result && getPassword()
            .equals(other.getPassword());
      }
      result = result && (hasRcAmount() == other.hasRcAmount());
      if (hasRcAmount()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getRcAmount())
            == java.lang.Double.doubleToLongBits(
                other.getRcAmount()));
      }
      result = result && (hasRole() == other.hasRole());
      if (hasRole()) {
        result = result && getRole()
            .equals(other.getRole());
      }
      result = result && (hasApproved() == other.hasApproved());
      if (hasApproved()) {
        result = result && (getApproved()
            == other.getApproved());
      }
      result = result && (hasMail() == other.hasMail());
      if (hasMail()) {
        result = result && getMail()
            .equals(other.getMail());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUserId()) {
        hash = (37 * hash) + USER_ID_FIELD_NUMBER;
        hash = (53 * hash) + getUserId();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasMobile()) {
        hash = (37 * hash) + MOBILE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMobile());
      }
      if (hasHumanId()) {
        hash = (37 * hash) + HUMAN_ID_FIELD_NUMBER;
        hash = (53 * hash) + getHumanId().hashCode();
      }
      if (hasPassword()) {
        hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getPassword().hashCode();
      }
      if (hasRcAmount()) {
        hash = (37 * hash) + RC_AMOUNT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getRcAmount()));
      }
      if (hasRole()) {
        hash = (37 * hash) + ROLE_FIELD_NUMBER;
        hash = (53 * hash) + getRole().hashCode();
      }
      if (hasApproved()) {
        hash = (37 * hash) + APPROVED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getApproved());
      }
      if (hasMail()) {
        hash = (37 * hash) + MAIL_FIELD_NUMBER;
        hash = (53 * hash) + getMail().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static user.ZCoin.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static user.ZCoin.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static user.ZCoin.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static user.ZCoin.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static user.ZCoin.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static user.ZCoin.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static user.ZCoin.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static user.ZCoin.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static user.ZCoin.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static user.ZCoin.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static user.ZCoin.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static user.ZCoin.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(user.ZCoin.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code user.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:user.User)
        user.ZCoin.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return user.ZCoin.internal_static_user_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return user.ZCoin.internal_static_user_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                user.ZCoin.User.class, user.ZCoin.User.Builder.class);
      }

      // Construct using user.ZCoin.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        mobile_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        humanId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        rcAmount_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        role_ = "user";
        bitField0_ = (bitField0_ & ~0x00000040);
        approved_ = false;
        bitField0_ = (bitField0_ & ~0x00000080);
        mail_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return user.ZCoin.internal_static_user_User_descriptor;
      }

      @java.lang.Override
      public user.ZCoin.User getDefaultInstanceForType() {
        return user.ZCoin.User.getDefaultInstance();
      }

      @java.lang.Override
      public user.ZCoin.User build() {
        user.ZCoin.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public user.ZCoin.User buildPartial() {
        user.ZCoin.User result = new user.ZCoin.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.mobile_ = mobile_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.humanId_ = humanId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.rcAmount_ = rcAmount_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.role_ = role_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.approved_ = approved_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.mail_ = mail_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof user.ZCoin.User) {
          return mergeFrom((user.ZCoin.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(user.ZCoin.User other) {
        if (other == user.ZCoin.User.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasMobile()) {
          setMobile(other.getMobile());
        }
        if (other.hasHumanId()) {
          bitField0_ |= 0x00000008;
          humanId_ = other.humanId_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000010;
          password_ = other.password_;
          onChanged();
        }
        if (other.hasRcAmount()) {
          setRcAmount(other.getRcAmount());
        }
        if (other.hasRole()) {
          bitField0_ |= 0x00000040;
          role_ = other.role_;
          onChanged();
        }
        if (other.hasApproved()) {
          setApproved(other.getApproved());
        }
        if (other.hasMail()) {
          bitField0_ |= 0x00000100;
          mail_ = other.mail_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        user.ZCoin.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (user.ZCoin.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int userId_ ;
      /**
       * <code>optional int32 user_id = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 user_id = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>optional int32 user_id = 1;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 user_id = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private long mobile_ ;
      /**
       * <code>optional int64 mobile = 3;</code>
       */
      public boolean hasMobile() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 mobile = 3;</code>
       */
      public long getMobile() {
        return mobile_;
      }
      /**
       * <code>optional int64 mobile = 3;</code>
       */
      public Builder setMobile(long value) {
        bitField0_ |= 0x00000004;
        mobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 mobile = 3;</code>
       */
      public Builder clearMobile() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mobile_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object humanId_ = "";
      /**
       * <code>optional string human_id = 4;</code>
       */
      public boolean hasHumanId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string human_id = 4;</code>
       */
      public java.lang.String getHumanId() {
        java.lang.Object ref = humanId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            humanId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string human_id = 4;</code>
       */
      public com.google.protobuf.ByteString
          getHumanIdBytes() {
        java.lang.Object ref = humanId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          humanId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string human_id = 4;</code>
       */
      public Builder setHumanId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        humanId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string human_id = 4;</code>
       */
      public Builder clearHumanId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        humanId_ = getDefaultInstance().getHumanId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string human_id = 4;</code>
       */
      public Builder setHumanIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        humanId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>optional string password = 5;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string password = 5;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string password = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 5;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 5;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000010);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 5;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        password_ = value;
        onChanged();
        return this;
      }

      private double rcAmount_ ;
      /**
       * <code>optional double rc_amount = 6;</code>
       */
      public boolean hasRcAmount() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional double rc_amount = 6;</code>
       */
      public double getRcAmount() {
        return rcAmount_;
      }
      /**
       * <code>optional double rc_amount = 6;</code>
       */
      public Builder setRcAmount(double value) {
        bitField0_ |= 0x00000020;
        rcAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double rc_amount = 6;</code>
       */
      public Builder clearRcAmount() {
        bitField0_ = (bitField0_ & ~0x00000020);
        rcAmount_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object role_ = "user";
      /**
       * <code>optional string role = 7 [default = "user"];</code>
       */
      public boolean hasRole() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string role = 7 [default = "user"];</code>
       */
      public java.lang.String getRole() {
        java.lang.Object ref = role_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            role_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string role = 7 [default = "user"];</code>
       */
      public com.google.protobuf.ByteString
          getRoleBytes() {
        java.lang.Object ref = role_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          role_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string role = 7 [default = "user"];</code>
       */
      public Builder setRole(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        role_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string role = 7 [default = "user"];</code>
       */
      public Builder clearRole() {
        bitField0_ = (bitField0_ & ~0x00000040);
        role_ = getDefaultInstance().getRole();
        onChanged();
        return this;
      }
      /**
       * <code>optional string role = 7 [default = "user"];</code>
       */
      public Builder setRoleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        role_ = value;
        onChanged();
        return this;
      }

      private boolean approved_ ;
      /**
       * <code>optional bool approved = 8 [default = false];</code>
       */
      public boolean hasApproved() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional bool approved = 8 [default = false];</code>
       */
      public boolean getApproved() {
        return approved_;
      }
      /**
       * <code>optional bool approved = 8 [default = false];</code>
       */
      public Builder setApproved(boolean value) {
        bitField0_ |= 0x00000080;
        approved_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool approved = 8 [default = false];</code>
       */
      public Builder clearApproved() {
        bitField0_ = (bitField0_ & ~0x00000080);
        approved_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object mail_ = "";
      /**
       * <code>optional string mail = 9;</code>
       */
      public boolean hasMail() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string mail = 9;</code>
       */
      public java.lang.String getMail() {
        java.lang.Object ref = mail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mail_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mail = 9;</code>
       */
      public com.google.protobuf.ByteString
          getMailBytes() {
        java.lang.Object ref = mail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mail = 9;</code>
       */
      public Builder setMail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        mail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mail = 9;</code>
       */
      public Builder clearMail() {
        bitField0_ = (bitField0_ & ~0x00000100);
        mail_ = getDefaultInstance().getMail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mail = 9;</code>
       */
      public Builder setMailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        mail_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:user.User)
    }

    // @@protoc_insertion_point(class_scope:user.User)
    private static final user.ZCoin.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new user.ZCoin.User();
    }

    public static user.ZCoin.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public user.ZCoin.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\004user\"\247\001\n\004User\022\017\n\007user_id\030\001" +
      " \001(\005\022\014\n\004name\030\002 \001(\t\022\016\n\006mobile\030\003 \001(\003\022\020\n\010hu" +
      "man_id\030\004 \001(\t\022\020\n\010password\030\005 \001(\t\022\021\n\trc_amo" +
      "unt\030\006 \001(\001\022\022\n\004role\030\007 \001(\t:\004user\022\027\n\010approve" +
      "d\030\010 \001(\010:\005false\022\014\n\004mail\030\t \001(\tB\r\n\004userB\005ZC" +
      "oin"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_user_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_User_descriptor,
        new java.lang.String[] { "UserId", "Name", "Mobile", "HumanId", "Password", "RcAmount", "Role", "Approved", "Mail", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
