// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package account;

public final class ZCoin {
  private ZCoin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AccountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:account.Account)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 user_id = 1;</code>
     */
    int getUserId();

    /**
     * <code>int32 account_num = 2;</code>
     */
    int getAccountNum();

    /**
     * <code>double rc_amount = 3;</code>
     */
    double getRcAmount();

    /**
     * <code>double zc_amount = 4;</code>
     */
    double getZcAmount();
  }
  /**
   * Protobuf type {@code account.Account}
   */
  public  static final class Account extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:account.Account)
      AccountOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Account.newBuilder() to construct.
    private Account(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Account() {
      userId_ = 0;
      accountNum_ = 0;
      rcAmount_ = 0D;
      zcAmount_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Account(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              userId_ = input.readInt32();
              break;
            }
            case 16: {

              accountNum_ = input.readInt32();
              break;
            }
            case 25: {

              rcAmount_ = input.readDouble();
              break;
            }
            case 33: {

              zcAmount_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return account.ZCoin.internal_static_account_Account_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return account.ZCoin.internal_static_account_Account_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              account.ZCoin.Account.class, account.ZCoin.Account.Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>int32 user_id = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int ACCOUNT_NUM_FIELD_NUMBER = 2;
    private int accountNum_;
    /**
     * <code>int32 account_num = 2;</code>
     */
    public int getAccountNum() {
      return accountNum_;
    }

    public static final int RC_AMOUNT_FIELD_NUMBER = 3;
    private double rcAmount_;
    /**
     * <code>double rc_amount = 3;</code>
     */
    public double getRcAmount() {
      return rcAmount_;
    }

    public static final int ZC_AMOUNT_FIELD_NUMBER = 4;
    private double zcAmount_;
    /**
     * <code>double zc_amount = 4;</code>
     */
    public double getZcAmount() {
      return zcAmount_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0) {
        output.writeInt32(1, userId_);
      }
      if (accountNum_ != 0) {
        output.writeInt32(2, accountNum_);
      }
      if (rcAmount_ != 0D) {
        output.writeDouble(3, rcAmount_);
      }
      if (zcAmount_ != 0D) {
        output.writeDouble(4, zcAmount_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (accountNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, accountNum_);
      }
      if (rcAmount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, rcAmount_);
      }
      if (zcAmount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, zcAmount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof account.ZCoin.Account)) {
        return super.equals(obj);
      }
      account.ZCoin.Account other = (account.ZCoin.Account) obj;

      boolean result = true;
      result = result && (getUserId()
          == other.getUserId());
      result = result && (getAccountNum()
          == other.getAccountNum());
      result = result && (
          java.lang.Double.doubleToLongBits(getRcAmount())
          == java.lang.Double.doubleToLongBits(
              other.getRcAmount()));
      result = result && (
          java.lang.Double.doubleToLongBits(getZcAmount())
          == java.lang.Double.doubleToLongBits(
              other.getZcAmount()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + ACCOUNT_NUM_FIELD_NUMBER;
      hash = (53 * hash) + getAccountNum();
      hash = (37 * hash) + RC_AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getRcAmount()));
      hash = (37 * hash) + ZC_AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getZcAmount()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static account.ZCoin.Account parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static account.ZCoin.Account parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static account.ZCoin.Account parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static account.ZCoin.Account parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static account.ZCoin.Account parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static account.ZCoin.Account parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static account.ZCoin.Account parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static account.ZCoin.Account parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static account.ZCoin.Account parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static account.ZCoin.Account parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static account.ZCoin.Account parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static account.ZCoin.Account parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(account.ZCoin.Account prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code account.Account}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:account.Account)
        account.ZCoin.AccountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return account.ZCoin.internal_static_account_Account_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return account.ZCoin.internal_static_account_Account_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                account.ZCoin.Account.class, account.ZCoin.Account.Builder.class);
      }

      // Construct using account.ZCoin.Account.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = 0;

        accountNum_ = 0;

        rcAmount_ = 0D;

        zcAmount_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return account.ZCoin.internal_static_account_Account_descriptor;
      }

      @java.lang.Override
      public account.ZCoin.Account getDefaultInstanceForType() {
        return account.ZCoin.Account.getDefaultInstance();
      }

      @java.lang.Override
      public account.ZCoin.Account build() {
        account.ZCoin.Account result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public account.ZCoin.Account buildPartial() {
        account.ZCoin.Account result = new account.ZCoin.Account(this);
        result.userId_ = userId_;
        result.accountNum_ = accountNum_;
        result.rcAmount_ = rcAmount_;
        result.zcAmount_ = zcAmount_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof account.ZCoin.Account) {
          return mergeFrom((account.ZCoin.Account)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(account.ZCoin.Account other) {
        if (other == account.ZCoin.Account.getDefaultInstance()) return this;
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (other.getAccountNum() != 0) {
          setAccountNum(other.getAccountNum());
        }
        if (other.getRcAmount() != 0D) {
          setRcAmount(other.getRcAmount());
        }
        if (other.getZcAmount() != 0D) {
          setZcAmount(other.getZcAmount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        account.ZCoin.Account parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (account.ZCoin.Account) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int userId_ ;
      /**
       * <code>int32 user_id = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>int32 user_id = 1;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 user_id = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private int accountNum_ ;
      /**
       * <code>int32 account_num = 2;</code>
       */
      public int getAccountNum() {
        return accountNum_;
      }
      /**
       * <code>int32 account_num = 2;</code>
       */
      public Builder setAccountNum(int value) {
        
        accountNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 account_num = 2;</code>
       */
      public Builder clearAccountNum() {
        
        accountNum_ = 0;
        onChanged();
        return this;
      }

      private double rcAmount_ ;
      /**
       * <code>double rc_amount = 3;</code>
       */
      public double getRcAmount() {
        return rcAmount_;
      }
      /**
       * <code>double rc_amount = 3;</code>
       */
      public Builder setRcAmount(double value) {
        
        rcAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double rc_amount = 3;</code>
       */
      public Builder clearRcAmount() {
        
        rcAmount_ = 0D;
        onChanged();
        return this;
      }

      private double zcAmount_ ;
      /**
       * <code>double zc_amount = 4;</code>
       */
      public double getZcAmount() {
        return zcAmount_;
      }
      /**
       * <code>double zc_amount = 4;</code>
       */
      public Builder setZcAmount(double value) {
        
        zcAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double zc_amount = 4;</code>
       */
      public Builder clearZcAmount() {
        
        zcAmount_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:account.Account)
    }

    // @@protoc_insertion_point(class_scope:account.Account)
    private static final account.ZCoin.Account DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new account.ZCoin.Account();
    }

    public static account.ZCoin.Account getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Account>
        PARSER = new com.google.protobuf.AbstractParser<Account>() {
      @java.lang.Override
      public Account parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Account(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Account> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Account> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public account.ZCoin.Account getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_account_Account_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_account_Account_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\raccount.proto\022\007account\"U\n\007Account\022\017\n\007u" +
      "ser_id\030\001 \001(\005\022\023\n\013account_num\030\002 \001(\005\022\021\n\trc_" +
      "amount\030\003 \001(\001\022\021\n\tzc_amount\030\004 \001(\001B\020\n\007accou" +
      "ntB\005ZCoinb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_account_Account_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_account_Account_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_account_Account_descriptor,
        new java.lang.String[] { "UserId", "AccountNum", "RcAmount", "ZcAmount", });
  }
@Override
public String toString() {
	
	return "Account num : "+account.ZCoin.Account.newBuilder().accountNum_+"\nUser Id : "+
account.ZCoin.Account.newBuilder().userId_+"\nRc Amount : "+account.ZCoin.Account.newBuilder().rcAmount_
+"\nZC Amount : "+account.ZCoin.Account.newBuilder().zcAmount_;
}
  
 

  // @@protoc_insertion_point(outer_class_scope)
}
